---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
  csi:
    driver: glusterfs.csi.k8s.io
    readOnly: false
    volumeHandle: 8dd8cb13-dd16-419e-b89c-b6536c0c35d6 # Run uuidgen to generate a unique id
    volumeAttributes:
      server: gluster-0.okd.local
      share: /data/static-0

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: static-0
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: static-pv
  storageClassName: ""


